{% set version = "1.3.0" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-pinfsc50
  version: {{ version|replace("-", "_") }}

source:
  fn: pinfsc50_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/pinfsc50_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/pinfsc50/pinfsc50_{{ version }}.tar.gz

  sha256: 971627cf4567fdb34db26010f2db44cfac5ff07f327d3247e778638cc4e849bf

build:
  noarch: generic
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('pinfsc50')"  # [not win]
    - "\"%R%\" -e \"library('pinfsc50')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=pinfsc50
  license: GPL
  summary: Genomic data for the plant pathogen "Phytophthora infestans." It includes a variant file ('VCF'), a sequence file ('FASTA') and an annotation file ('GFF'). This package is intended to be used as example data for packages that work with genomic data.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
