appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: G0CyvSwhWf2Dt5+Jkdj7Dy4XLseHgW7bK7SZnzqTGGk1hPQ71L2B8GXm9QAT3G3pR7Y5MOK31po9YyWw0W22YMpEU6f/7jhMbpvTmgWzCy76n74CiiiC0sN950Vuss5CziRK4pqzTQpJI5X4le0jCWlSlI3XqU2THkUR+zB4j0wFlLvnpggLGTXw+gt+RfFnwRy3fbxv4cyop361VIwvQLo6I92OwLcKQnz4SRCby82q/ORkUS55RGoN/qljncLjCeqfm6kv08WK8KUxFUybj5hsiFY6odjyfYpx9/mqgPHC7DpNvKqkUTYq4KCny8u/lLBDdaGn7XsAvw3fWKRG9AZ0oWK/f6xXYuXFah9hM+vIOnbBVR8ktb6nS8vTMPV584xqdWSHbGwE93rtOQNac3SnCa1QV4qWLnct3GSAYLsJVEi+XaCaqnFnffi711k8qm6tsCHV8AlC5fhM81zqvqXaRJ56VKZVr0oglfOZPfEK/gfjMUhBwr64tZBQNH5ngFEPvk1Kzh3tu0HfIa0KAZkGn0aiTulLnrsbjfZsLzU1mVQAzEcO+2+WoMzHF+JO1zxsdUrnuGNnDLkHnFTla8iJ8UhX1Anzn1suV5hw8dILAC/StwgmvNe8CRu7ljdHQpfvF7+yztW1nlsG6glRa30h14ligW9ncjuGl3xnypw=}
bot:
  automerge: true
