travis:
  secure:
    BINSTAR_TOKEN: RGLtKVgcw+5BSYq1gvOdQ3nGZYRvW3IZbe9sPKmn18T0NhQO5LyoazHQd4meaxTMXAkrBOAHA0FzEZKIF02lHin3RjXAZ6AQyHD3C+G9tizPWtcmdSxMGkjytybgdPE3wMnxZlVd3KEX2C8O127Zfuv1C5eGZeHFZXS5Q/opnojffuLCe/N5anHW53i2YRgzQfuAWlNsgkQJXaTQD0GDJikYD0FMbhomnZmvekTq5znzUT7FlGS4cF1YHAW8jRfGi43eDE9b/OPw+MBsppRE79Hvac0xKHqr9uTEpT6rrVL3I98Tf/40B8eDikEGtr8697sh8RSV7YtIehEKIow75BoXFOPW79HOvYdF5UuPPo1HrodsyKveyKWyT4srkG6q3yNOSL+8BNl4bC0slanfMXF4y+LjVWqtTCCddeiqAKaf0NfuEUVp6jN96NBLeyXiqIedbmmHy91GnZNZIaWg0A9JxKodrhTd0fQCcH5ZGAeYNJiFCn9RZC+Rx1AVvkoln4kHAKN/oSmHV76j7Gywa3ZqSBZqSbqB74QMgU6UZ5Ln32g2necK+fDeDesU11PzCdXoRbrY0Mb6DUtwGPpdXnEI5roO6isB8bo5Qhjf4dMsiYbztXftjwQRnUYc/QqYAv5YUZ1MHfLKFMy1ZiCcRKB2DegzJN0kW6aaqtM2wpc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
